name: Playwright
on:
  pull_request:
  push:
    branches: main
  schedule:
    # At 08:00 daily - good for keeping up with latest WP releases
    - cron: '0 8 * * *'

jobs:
  playwright:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      id: setup-node
      with:
        node-version: lts/*
        cache: 'npm'
        cache-dependency-path: |
          package-lock.json
          package.json

    - name: Cache Playwright browsers
      id: cache-browsers
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/ms-playwright
        key: playwright-${{ runner.os }}-${{ hashFiles('package-lock.json', 'package.json') }}
        restore-keys: |
          playwright-${{ runner.os }}-

    - name: Cache node_modules and npm cache
      id: cache-node-modules
      uses: actions/cache@v4
      with:
        path: |
          node_modules
          ~/.npm
        key: ${{ runner.os }}-node-${{ steps.setup-node.outputs.node-version }}-npm-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ steps.setup-node.outputs.node-version }}-npm-

    - name: Install dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: npm ci --prefer-offline --no-audit --no-fund

    - name: Install Playwright Browsers
      if: steps.cache-browsers.outputs.cache-hit != 'true'
      run: npx playwright install --with-deps

    - name: Build project
      run: npm run build
      env:
        CI: true

    - name: Run Playwright tests
      run: npx playwright test

    - name: Update README last passed
      if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'schedule' && success() }}
      run: |
        git config user.name "extendify-ci"
        git config user.email "dev@extendify.com"
        ts="$(date -u '+%Y-%m-%d %H:%M:%S UTC')"

        # Remove any existing timestamp comments and add a new one
        sed -i -E '/Playwright last run/d' README.md || true
        printf "\n<!-- Playwright last run: %s -->\n" "$ts" >> README.md

        git add README.md
        git diff --cached --quiet && exit 0
        git commit -m "chore(ci): update last passed at $ts"
        git push

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
