name: Playwright Tests
on:
  pull_request:
  push:
    branches: main
  schedule:
    # At 08:00 daily - good for keeping up with latest WP releases
    - cron: '0 8 * * *'

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'npm'
        cache-dependency-path: |
          package-lock.json
          package.json

    - name: Cache Playwright browsers
      id: cache-browsers
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/ms-playwright
        key: playwright-${{ runner.os }}-${{ hashFiles('package-lock.json', 'package.json') }}
        restore-keys: |
          playwright-${{ runner.os }}-

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      if: steps.cache-browsers.outputs.cache-hit != 'true'
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test

    - name: Update README last passed
      if: ${{ github.ref == 'refs/heads/main' && success() }}
      run: |
        git config user.name "extendify-ci"
        git config user.email "dev@extendify.com"
        ts="$(date -u '+%Y-%m-%d %H:%M:%S UTC')"
        sed -i.bak -E 's|(<!-- last-pass:start -->).*(<!-- last-pass:end -->)|\1 Last passed: '"$ts"' \2|' README.md || true
        if ! grep -q '<!-- last-pass:start -->' README.md; then
          printf "\n\n<!-- last-pass:start -->Last passed: %s <!-- last-pass:end -->\n" "$ts" >> README.md
        fi
        rm -f README.md.bak
        git add README.md
        git diff --cached --quiet && exit 0
        git commit -m "chore(ci): update last passed at $ts"
        git push

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
